# **Numpy Array Operations:**

In [1]:

#Create a 1D NumPy Array

import numpy as np

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)



[22.5 25.3 20.8 23.4 26.1 24.8 21.9]


In [2]:

# Inspecting properties

print("Shape:", temperatures_w1.shape)
print("Data Type:", temperatures_w1.dtype)
print("Number of Elements:", temperatures_w1.size)


Shape: (7,)
Data Type: float64
Number of Elements: 7


In [3]:

# Convert Celsius to Fahrenheit

temperatures_f = (temperatures_w1 * 9/5) + 32
print("Temperatures in Fahrenheit:", temperatures_f)

# Find maximum, minimum, and mean

max_temp = np.max(temperatures_w1)
min_temp = np.min(temperatures_w1)
mean_temp = np.mean(temperatures_w1)

print("Maximum Temperature (°C):", max_temp)
print("Minimum Temperature (°C):", min_temp)
print("Mean Temperature (°C):", mean_temp)


Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum Temperature (°C): 26.1
Minimum Temperature (°C): 20.8
Mean Temperature (°C): 23.542857142857144


In [4]:

# First three days (indices 0,1,2)

first_three = temperatures_w1[:3]
print("First three days:", first_three)

# Weekend (last two days → indices 5,6)

weekend = temperatures_w1[-2:]
print("Weekend temperatures:", weekend)

# Middle three days (indices 2,3,4)

middle_three = temperatures_w1[2:5]
print("Middle three days:", middle_three)


First three days: [22.5 25.3 20.8]
Weekend temperatures: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]


In [5]:

# Week 1 and Week 2 data

week1 = [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
week2 = [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]

temperatures = np.array([week1, week2])
print("Temperatures 2D array:")
print(temperatures)


Temperatures 2D array:
[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]


In [6]:

#Inspection

print("Shape:", temperatures.shape)
print("Data Type:", temperatures.dtype)
print("Total Number of Elements:", temperatures.size)

#Slicing

# Extract temperatures for Week 1

week1_temps = temperatures[0]
print("Week 1 Temperatures:", week1_temps)

# Extract temperatures for Week 2

week2_temps = temperatures[1]
print("Week 2 Temperatures:", week2_temps)

# Weekend for both weeks (last two days → columns -2 and -1)

weekend_temps = temperatures[:, -2:]
print("Weekend Temperatures for Both Weeks:")
print(weekend_temps)


Shape: (2, 7)
Data Type: float64
Total Number of Elements: 14
Week 1 Temperatures: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2 Temperatures: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Weekend Temperatures for Both Weeks:
[[24.8 21.9]
 [22.8 20.1]]


# **Pandas Series:**

In [10]:

import pandas as pd

# Creating a Pandas Series

marks = pd.Series(
    [95, 92, 89, 85, 80],
    index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5']
)

print(marks)



Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64


In [11]:

marks[0]

marks.loc[['Rank1', 'Rank2', 'Rank3']]

marks.iloc[2]

marks[marks > 90]



/tmp/ipython-input-3512584167.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  marks[0]


Rank1    95
Rank2    92
dtype: int64

In [12]:

marks['Rank1'] = 100

marks = marks.drop('Rank5')

cgpa = marks / 10
print(cgpa)


Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64


# **Pandas DataFrame:**

In [13]:

# Creating the DataFrame

transactions = pd.DataFrame({
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture',
                        'Clothing', 'Electronics', 'Furniture', 'Clothing',
                        'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East',
               'West', 'South', 'North'],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})

# Display the DataFrame

print(transactions)


   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400


In [15]:

#Display the DataFrame and its basic information

print(transactions)
print(transactions.head())
print(transactions.tail())
print(transactions.shape)
print(transactions.columns)
print(transactions.dtypes)

#Display only 'ProductCategory' and 'Amount' columns

print(transactions[['ProductCategory', 'Amount']])

#Retrieve the last 3 columns using iloc

print(transactions.iloc[:, -3:])

print(transactions.loc[:, ['ProductCategory', 'Region', 'Amount']])

#Filter rows where Region = 'North' AND Amount > 200

filtered_data = transactions[(transactions['Region'] == 'North') &
                             (transactions['Amount'] > 200)]
print(filtered_data)

#Value counts for ProductCategory

print(transactions['ProductCategory'].value_counts())

#Unique values in Region

print(transactions['Region'].unique())

#Group by Region and find mean Amount

mean_by_region = transactions.groupby('Region')['Amount'].mean()
print(mean_by_region)












   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West 

In [17]:

#Modify the 'Amount' for TransactionID 102 → 165
transactions.loc[transactions['TransactionID'] == 102, 'Amount'] = 165

#Add a new column 'Discount' = 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10

#Remove the row with TransactionID 109
transactions = transactions[transactions['TransactionID'] != 109]

#Delete the 'Discount' column
transactions = transactions.drop('Discount', axis=1)

transactions

TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400